version: "3.8"
services:
  bot:
    build:
      context: ./
    restart: unless-stopped
    env_file: ./secrets.env
    init: true
    environment:
      USERS_SERVICE_TABLE_NAME: TonkatsuStack-users9E3E6EF7-19OQ46A0WAOHQ
      LEADERBOARD_CHANNEL_ID: 775606211952771100
      MINECRAFT_SERVER_NAME: Tonkatsu
      MINECRAFT_SERVER_HOST: mc.tonkat.su
      AWS_REGION: us-west-2
      GUILD_ID: 764720442250100700
      IMGUR_CLIENT_ID: 3b5d5f0ff8b8c29
