version: "3.8"
services:
  bot:
    build:
      context: ./
    restart: unless-stopped
    env_file: ./secrets.env
    init: true
    environment:
      USERS_SERVICE_REDIS_URL: redis://bot_redis/0
      LEADERBOARD_SERVICE_REDIS_URL: redis://bot_redis/1
      LEADERBOARD_CHANNEL_ID: 775577260127158282
      MINECRAFT_SERVER_NAME: NewPumpcraft
      MINECRAFT_SERVER_HOST: mc.sep.gg
      AWS_REGION: us-west-2
  bot_redis:
    image: redis:6-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: bot_redis
        target: /data

volumes:
  bot_redis: