version: "3.8"
services:
  bot:
    build:
      context: ./
    restart: unless-stopped
    env_file: ./docker.env
    init: true
    environment:
      USERS_SERVICE_REDIS_URL: redis://bot_redis/0
  bot_redis:
    image: redis:6-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: bot_redis
        target: /data

volumes:
  bot_redis: