on:
  push:
    branches:
      - main
  pull_request:
    branches:
name: build and push
jobs:
  bot:
    strategy:
      matrix:
        go-version: [1.17.1]
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker
        uses: docker/setup-buildx-action@v1
      - name: login to github docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: docker build and push
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.ref }}
      - name: docker build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest