on: [push]
jobs:
  cdk:
    needs: [build_binaries]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.72.0'
          working_dir: 'infra'
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'deploy'
          cdk_version: '1.72.0'
          working_dir: 'infra'
          actions_comment: false
          args: '--require-approval never'
        env:
          AWS_DEFAULT_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
