on:
  push:
    branches:
      - main
name: register discord commands
jobs:
  build_registration_script:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - name: checkout code
        uses: actions/checkout@v3
      - name: go build
        env:
          CGO_ENABLED: "0"
          GOOS: linux
        run: |
          mkdir build
          go build -a -ldflags='-extldflags=-static' -o ./build/ ./cmd/...
      - name: archive built binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ${{ github.workspace }}
  fetch_discord_token:
    runs-on: ubuntu-latest
    outputs:
      discord_token: ${{ steps.fetch_discord_token.outputs }}
    steps:
      - id: fetch_discord_token
        run: echo -n 'token=' && aws secretsmanager get-secret-value --secret-id discord-interactions-api --query SecretString --output text | jq .DISCORD_TOKEN
  register_discord_commands:
    needs: [build_registration_script, fetch_discord_token, cdk_deploy]
    runs-on: ubuntu-latest
    steps:
      - name: download binaries
        id: download
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ${{ github.workspace }}
      - name: fix executable permissions
        run: chmod 755 -R ${{ github.workspace }}/build
      - name: run register
        env:
          DISCORD_TOKEN: ${{ needs.fetch_discord_token.outputs.discord_token }}
