on: [push, pull_request]
name: build and push
jobs:
    pipeline:
        strategy:
            matrix:
                go-version: [^1.x]
        runs-on: ubuntu-latest
        steps:
            -
                name: install go
                uses: actions/setup-go@v2
                with:
                    go-version: ${{ matrix.go-version }}
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: setup qemu
                uses: docker/setup-qemu-action@v1
            -
                name: setup docker
                uses: docker/setup-buildx-action@v1
            -
                name: login to github docker registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.CR_PAT }}
            -
                name: docker build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ghcr.io/${{ github.repository }}:latest