on: [push, pull_request]
name: test and push
jobs:
    pipeline:
        strategy:
            matrix:
                go-version: [^1.x]
        runs-on: ubuntu-latest
        steps:
            -
                name: install go
                uses: actions/setup-go@v2
                with:
                    go-version: ${{ matrix.go-version }}
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: lint
                uses: actions-contrib/golangci-lint@v1
                with:
                    golangci_lint_version: latest
            -
                name: setup qemu
                uses: docker/setup-qemu-action@v1
            -
                name: setup docker
                uses: docker/setup-buildx-action@v1
            -
                name: login to github docker registry
                uses: docker/login-action@v1
                with:
                    registry: ghci.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: docker build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ghcr.io/tonkat-su/bot:latest
